import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Content from "@/components/Content";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>3.14159.mov - View a random Pi song video</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="description"
          content="3.14159.mov is a website where you can view a random Pi song video. Enjoy entertaining and educational songs about the mathematical constant Pi."
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="Pi, song video, circle, mathematics, entertainment" />
        <meta name="robots" content="index, follow" />

        <meta property="og:title" content="3.14159.mov - View a random Pi song video" />
        <meta
          property="og:description"
          content="3.14159.mov is a website where you can view a random Pi song video. Enjoy entertaining and educational songs about the mathematical constant Pi."
        />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://3.14159.mov" />
        <meta property="og:image" content="/pi.png" />

        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="3.14159.mov - View a random Pi song video" />
        <meta
          name="twitter:description"
          content="3.14159.mov is a website where you can view a random Pi song video. Enjoy entertaining and educational songs about the mathematical constant Pi."
        />
        <meta name="twitter:image" content="/pi.png" />

        <link rel="icon" href="/favicon.ico" />
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5420540802887052"
          crossOrigin="anonymous"
        ></script>
      </Head>
      <Header />
      <main className={styles.main}>
        <Content />
      </main>
    </>
  );
}
